### ISSUE TITLE
Fix blank page with mapped routes

### ISSUE THREAD

**Issue by NehemiahDias** [SWELLZ/flashcard#18]
When you edit and import decks, the decks will show on the review page but when clicked it leads to a blank page. The expected behavior should be: When you import or edit your deck, it should automatically add a route for that deck and bring you to a page with that deck's info when clicked.

What happens: It leads you to a blank page and data only populates when that page is refreshed or if you go back to the home page and refresh.

Possible Fixes:
- Redirect the user to the home page and refresh (most annoying and worst UX)
- Map the routes in the return function of the review component

**Comment by subashpaul** [comment]
can i work on this?

**Comment by NehemiahDias** [comment]
> can i work on this?
> 

Yeah, just fork the repo and run npm install when it's cloned.

**Comment by NehemiahDias** [comment]
> can i work on this?
To recreate this issue, you'll need to comment out the `setTimeout` part of the `onRenderLoad` function in `src/components/flashcardComponents/ReviewFlashcard.jsx`. You'll also need to comment the `setTimeout` part of the `handleSubmit` function in `src/components/flashcardComponents/EditDeck.jsx`

**Comment by subashpaul** [comment]
ok working on it...thanks for assigning

**Comment by NehemiahDias** [comment]
> ok working on it...thanks for assigning

No worries, all the work should be branched off of the iss7 branch or done directly in that branch. That's where all the authentication progress is. Thanks for working on it!

**Comment by subashpaul** [comment]
Raised PR #24 
Do check and let me know.
Thank You.
